language: php

php:
    - 5.6
    - 7.0
    - 7.1
    
sudo: false

before_install:
    # execute all of the commands which need to be executed 
    # before installing dependencies
#  - source .travis/xdebug.sh
#  - xdebug-disable
#  - composer validate


install:
    # install all of the dependencies we need here
    - composer install --prefer-dist

before_script:
    # execute all of the commands which need to be executed 
    # before running actual tests

script:
    # execute all of the tests or other commands to determine
    # whether the build will pass or fail
    - vendor/phpunit/phpunit/phpunit test-runner.php .

notifications:
  email: false
